[package]
name = "uv-publish-command"
version = "0.0.92"
description = "This is an internal component crate of uv"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
uv-auth = { workspace = true }
uv-cache = { workspace = true }
uv-cli-output = { workspace = true }
uv-cli-types = { workspace = true }
uv-client = { workspace = true }
uv-configuration = { workspace = true }
uv-console = { workspace = true }
uv-distribution-types = { workspace = true }
uv-errors = { workspace = true }
uv-publish = { workspace = true }
uv-redacted = { workspace = true }
uv-settings = { workspace = true }
uv-static = { workspace = true }
uv-warnings = { workspace = true }

anyhow = { workspace = true }
console = { workspace = true }
insta = { workspace = true }
owo-colors = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[features]
test = ["uv-publish/test"]
