//! Integration coverage for explicit arguments passed by embedded callers.
#![cfg(feature = "test-python")]

use std::ffi::OsString;
use std::process::Command;

use anyhow::Result;
use assert_cmd::assert::OutputAssertExt;
use assert_fs::fixture::{FileWriteStr, PathChild};
use clap::Parser;
use indoc::indoc;
use uv::GlobalInitialization;
use uv_cli::Cli;
use uv_command_support::ExitStatus;
use uv_test::apply_filters;

#[tokio::test]
async fn explicit_arguments_reach_requirement_headers() -> Result<()> {
    // TestContext initializes preview test mode; this exercises normal command initialization.
    let root = assert_fs::TempDir::new()?;
    let cache = root.child("cache");
    let venv = root.child(".venv");
    Command::new(uv_test::get_bin!())
        .args([
            "venv",
            "--python",
            "3.12",
            "--no-python-downloads",
            "--offline",
            "--no-config",
        ])
        .arg("--cache-dir")
        .arg(cache.path())
        .arg(venv.path())
        .assert()
        .success();
    root.child("pyproject.toml").write_str(indoc! {r#"
        [project]
        name = "example"
        version = "0.1.0"
        requires-python = ">=3.12"

        [tool.uv]
        package = false
    "#})?;
    root.child("uv.lock").write_str(indoc! {r#"
        version = 1
        revision = 5
        requires-python = ">=3.12"

        [[package]]
        name = "example"
        version = "0.1.0"
        source = { virtual = "." }
    "#})?;
    root.child("requirements.in").write_str("")?;
    let filters = [(
        regex::escape(&root.path().to_string_lossy()),
        "[TEMP_DIR]".to_string(),
    )];
    let common = vec![
        OsString::from("uv"),
        "--quiet".into(),
        "--offline".into(),
        "--no-config".into(),
        "--cache-dir".into(),
        cache.path().as_os_str().to_owned(),
        "--project".into(),
        root.path().as_os_str().to_owned(),
    ];
    let mut export_args = common.clone();
    export_args.extend([
        OsString::from("export"),
        "--frozen".into(),
        "--output-file".into(),
        root.child("export.txt").as_os_str().to_owned(),
    ]);
    let status = uv::run_with_args(
        Cli::try_parse_from(&export_args)?,
        GlobalInitialization::Initialize,
        export_args,
    )
    .await?;
    assert!(matches!(status, ExitStatus::Success));
    insta::assert_snapshot!(apply_filters(fs_err::read_to_string(root.child("export.txt"))?, filters.as_slice()).replace('\\', "/"), @r#"
    # This file was autogenerated by uv via the following command:
    #    uv --offline --no-config --cache-dir [TEMP_DIR]/cache --project [TEMP_DIR] export --frozen --output-file [TEMP_DIR]/export.txt
    "#);

    let mut compile_args = common;
    compile_args.extend([
        OsString::from("pip"),
        "compile".into(),
        root.child("requirements.in").as_os_str().to_owned(),
        "--python".into(),
        venv.path().as_os_str().to_owned(),
        "--output-file".into(),
        root.child("compiled.txt").as_os_str().to_owned(),
    ]);
    let status = uv::run_with_args(
        Cli::try_parse_from(&compile_args)?,
        GlobalInitialization::Reuse,
        compile_args,
    )
    .await?;
    assert!(matches!(status, ExitStatus::Success));
    insta::assert_snapshot!(apply_filters(fs_err::read_to_string(root.child("compiled.txt"))?, filters.as_slice()).replace('\\', "/"), @r#"
    # This file was autogenerated by uv via the following command:
    #    uv --offline --no-config --cache-dir [TEMP_DIR]/cache --project [TEMP_DIR] pip compile [TEMP_DIR]/requirements.in --python [TEMP_DIR]/.venv --output-file [TEMP_DIR]/compiled.txt
    "#);
    Ok(())
}
