[package]
name = "uv-pyproject-toml"
version = "0.0.77"
description = "A parser for pyproject.toml files"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
uv-normalize = { workspace = true }
uv-pep440 = { version = "0.0.77", path = "../uv-pep440" }
uv-pep508 = { version = "0.0.77", path = "../uv-pep508" }

indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
