# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate first-party Bazel targets without resolving or changing Cargo dependencies.

Run `uv run scripts/bazel/generate.py`, or add `--check` to detect stale files.
Dependency edges and features are resolved by rules_rs directly from Cargo.
"""

import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = "# Generated by scripts/bazel/generate.py. Do not edit.\n"

# Files outside Rust sources that production code reads at compile time.
COMPILE_DATA = {
    "uv": ["src/commands/suggestions.json"],
    "uv-build-frontend": ["src/pipreqs/mapping"],
    "uv-installer": ["src/pip_compileall.py"],
    "uv-python": ["python/**/*.py"],
    "uv-virtualenv": ["src/_virtualenv.py", "src/activator/*"],
}
BUILD_SCRIPT_DATA = {"uv-python": ["download-metadata.json"]}


def package_value(package, workspace_package, field, default=""):
    value = package.get(field, default)
    if isinstance(value, dict) and value.get("workspace"):
        return workspace_package[field]
    return value


def string_list(items):
    if len(items) < 2:
        return json.dumps(items)
    return "[\n" + "".join(f"        {json.dumps(item)},\n" for item in items) + "    ]"


def render(manifest_path, workspace_package):
    manifest = tomllib.loads(manifest_path.read_text())
    package = manifest["package"]
    library = manifest.get("lib", {})
    directory = manifest_path.parent
    crate_root = library.get("path", "src/lib.rs")
    if not (directory / crate_root).is_file():
        crate_root = None
        if not (directory / "src/main.rs").is_file():
            raise ValueError(
                f"No crate entry point for {manifest_path.relative_to(ROOT)}"
            )

    def value(field, default=""):
        return package_value(package, workspace_package, field, default)

    cargo_env = {
        "CARGO_PKG_AUTHORS": ":".join(value("authors", [])),
        "CARGO_PKG_DESCRIPTION": value("description"),
        "CARGO_PKG_HOMEPAGE": value("homepage"),
        "CARGO_PKG_NAME": package["name"],
        "CARGO_PKG_REPOSITORY": value("repository"),
    }
    attributes = {
        "cargo_env": "{\n"
        + "".join(
            f"        {json.dumps(key)}: {json.dumps(item)},\n"
            for key, item in cargo_env.items()
        )
        + "    }",
        "edition": json.dumps(value("edition", "2015")),
        "version": json.dumps(value("version")),
    }

    crate_name = library.get("name", package["name"].replace("-", "_"))
    if crate_name != directory.name.replace("-", "_"):
        attributes["crate_name"] = json.dumps(crate_name)
    if crate_root is None:
        attributes["crate_root"] = "None"
    elif crate_root != "src/lib.rs":
        attributes["crate_root"] = json.dumps(crate_root)
    if library.get("proc-macro"):
        attributes["proc_macro"] = "True"
    if package["name"] in BUILD_SCRIPT_DATA:
        attributes["build_script_data"] = string_list(
            BUILD_SCRIPT_DATA[package["name"]]
        )
    if package["name"] in COMPILE_DATA:
        paths = COMPILE_DATA[package["name"]]
        files = [path for path in paths if "*" not in path]
        patterns = [path for path in paths if "*" in path]
        expressions = [string_list(files)] if files else []
        if patterns:
            expressions.append(f"glob({string_list(patterns)})")
        attributes["compile_data"] = " + ".join(expressions)
    if package["name"] == "uv":
        attributes["binary"] = '"src/bin/uv.rs"'
    elif crate_root is None:
        attributes["binary"] = '"src/main.rs"'
    if package["name"] == "uv-pep440":
        attributes["unit_test"] = "True"

    lines = [
        HEADER.rstrip(),
        'load("//bazel:rust.bzl", "uv_rust_crate")',
        "",
        "uv_rust_crate(",
        f"    name = {json.dumps(directory.name)},",
    ]
    # Buildifier keeps name first, then sorts the remaining attributes.
    for key, item in sorted(attributes.items()):
        lines.append(f"    {key} = {item},")
    lines.extend([")", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Report stale generated files"
    )
    args = parser.parse_args()
    workspace = tomllib.loads((ROOT / "Cargo.toml").read_text())["workspace"]
    excluded = {
        directory
        for pattern in workspace.get("exclude", [])
        for directory in ROOT.glob(pattern)
    }
    members = sorted(
        {
            directory / "Cargo.toml"
            for pattern in workspace["members"]
            for directory in ROOT.glob(pattern)
            if directory not in excluded and (directory / "Cargo.toml").is_file()
        }
    )

    stale = []
    for manifest_path in members:
        target = manifest_path.with_name("BUILD.bazel")
        content = render(manifest_path, workspace.get("package", {}))
        if target.is_file() and target.read_text() == content:
            continue
        if args.check:
            stale.append(str(target.relative_to(ROOT)))
        else:
            target.write_text(content)

    if stale:
        print("Stale Bazel targets:\n" + "\n".join(stale), file=sys.stderr)
        return 1
    action = "Checked" if args.check else "Generated"
    print(f"{action} {len(members)} Cargo workspace crate targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
