[package]
name = "uv-cli-common"
version = "0.0.91"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
uv-bin-install = { workspace = true }
uv-cache = { workspace = true }
uv-cli = { workspace = true }
uv-configuration = { workspace = true }
uv-console = { workspace = true }
uv-distribution = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-distribution-types = { workspace = true }
uv-fs = { workspace = true }
uv-install-wheel = { workspace = true }
uv-installer = { workspace = true }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-publish = { workspace = true }
uv-python-interpreter = { workspace = true }
uv-python-managed = { workspace = true }
uv-python-types = { workspace = true }
uv-redacted = { workspace = true }
uv-resolver = { workspace = true }
uv-settings = { workspace = true }
uv-shell = { workspace = true }
uv-static = { workspace = true }
uv-torch = { workspace = true }
uv-warnings = { workspace = true }
uv-workspace = { workspace = true }

anstream = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
fs-err = { workspace = true }
indicatif = { workspace = true }
owo-colors = { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }
