on:
  workflow_call:
    inputs:
      save-rust-cache:
        required: false
        type: string
        default: "true"
      test-macos:
        required: false
        type: string
        default: "false"
      linux-shards:
        required: false
        type: number
        default: 1
      macos-shards:
        required: false
        type: number
        default: 2
      windows-shards:
        required: false
        type: number
        default: 3

permissions:
  contents: read

jobs:
  cargo-test-linux:
    name: cargo test on linux
    uses: astral-sh/github-actions/.github/workflows/nextest.yml@583fb5711db77c8554775b551079742d8a341e91
    with:
      runs-on: depot-ubuntu-24.04-16
      timeout-minutes: 10
      shards: ${{ inputs.linux-shards }}
      save-cache: ${{ inputs.save-rust-cache == 'true' }}

  cargo-test-macos:
    name: cargo test on macos
    # Run macOS tests on main, or when the CI plan opts in.
    if: ${{ inputs.test-macos == 'true' }}
    uses: astral-sh/github-actions/.github/workflows/nextest.yml@583fb5711db77c8554775b551079742d8a341e91
    with:
      runs-on: namespace-profile-macos-15
      timeout-minutes: 20
      shards: ${{ github.ref == 'refs/heads/main' && 1 || inputs.macos-shards }}
      save-cache: ${{ inputs.save-rust-cache == 'true' }}

  cargo-test-windows:
    name: cargo test on windows
    uses: astral-sh/github-actions/.github/workflows/nextest.yml@583fb5711db77c8554775b551079742d8a341e91
    with:
      runs-on: namespace-profile-windows-2022-x86-64-16x32
      timeout-minutes: 15
      shards: ${{ inputs.windows-shards }}
      save-cache: ${{ inputs.save-rust-cache == 'true' }}
